export interface PermissionDef {
  code: string;
  module: string;
  resource: string;
  action: string;
  description: string;
}

export const PERMISSIONS: PermissionDef[] = [
  // ===== DASHBOARD =====
  { code: "dashboard.view", module: "DASHBOARD", resource: "dashboard", action: "view", description: "View dashboards" },
  { code: "dashboard.view_all_branches", module: "DASHBOARD", resource: "dashboard", action: "view_all_branches", description: "View dashboards for all branches" },

  // ===== COMPANY / BRANCH / ORG =====
  { code: "company.view", module: "COMPANY", resource: "company", action: "view", description: "View company configuration" },
  { code: "company.edit", module: "COMPANY", resource: "company", action: "edit", description: "Edit company configuration" },
  { code: "branch.view", module: "ORG", resource: "branch", action: "view", description: "View branches" },
  { code: "branch.create", module: "ORG", resource: "branch", action: "create", description: "Create branches" },
  { code: "branch.edit", module: "ORG", resource: "branch", action: "edit", description: "Edit branches" },
  { code: "branch.delete", module: "ORG", resource: "branch", action: "delete", description: "Deactivate branches" },
  { code: "branch.view_other_branches", module: "ORG", resource: "branch", action: "view_other_branches", description: "View other branches' data" },
  { code: "warehouse.view", module: "ORG", resource: "warehouse", action: "view", description: "View warehouses" },
  { code: "warehouse.create", module: "ORG", resource: "warehouse", action: "create", description: "Create warehouses" },
  { code: "warehouse.edit", module: "ORG", resource: "warehouse", action: "edit", description: "Edit warehouses" },
  { code: "location.view", module: "ORG", resource: "location", action: "view", description: "View stock locations" },
  { code: "department.view", module: "ORG", resource: "department", action: "view", description: "View departments" },
  { code: "department.edit", module: "ORG", resource: "department", action: "edit", description: "Edit departments" },
  { code: "costcentre.view", module: "ORG", resource: "costcentre", action: "view", description: "View cost/profit centres" },
  { code: "costcentre.edit", module: "ORG", resource: "costcentre", action: "edit", description: "Edit cost/profit centres" },

  // ===== USERS & ROLES =====
  { code: "user.view", module: "USERS", resource: "user", action: "view", description: "View users" },
  { code: "user.create", module: "USERS", resource: "user", action: "create", description: "Create users" },
  { code: "user.edit", module: "USERS", resource: "user", action: "edit", description: "Edit users" },
  { code: "user.delete", module: "USERS", resource: "user", action: "delete", description: "Deactivate users" },
  { code: "role.view", module: "USERS", resource: "role", action: "view", description: "View roles" },
  { code: "role.create", module: "USERS", resource: "role", action: "create", description: "Create roles" },
  { code: "role.edit", module: "USERS", resource: "role", action: "edit", description: "Edit roles and permissions" },
  { code: "role.delete", module: "USERS", resource: "role", action: "delete", description: "Delete roles" },

  // ===== PRODUCTS =====
  { code: "product.view", module: "PRODUCTS", resource: "product", action: "view", description: "View products" },
  { code: "product.create", module: "PRODUCTS", resource: "product", action: "create", description: "Create products" },
  { code: "product.edit", module: "PRODUCTS", resource: "product", action: "edit", description: "Edit products" },
  { code: "product.delete", module: "PRODUCTS", resource: "product", action: "delete", description: "Deactivate products" },
  { code: "product.import", module: "PRODUCTS", resource: "product", action: "import", description: "Import products (CSV/Excel)" },
  { code: "product.export", module: "PRODUCTS", resource: "product", action: "export", description: "Export products" },
  { code: "product.price_change", module: "PRODUCTS", resource: "product", action: "price_change", description: "Change product prices" },
  { code: "product.view_cost", module: "PRODUCTS", resource: "product", action: "view_cost", description: "View product cost prices" },
  { code: "category.view", module: "PRODUCTS", resource: "category", action: "view", description: "View categories" },
  { code: "category.edit", module: "PRODUCTS", resource: "category", action: "edit", description: "Manage categories, brands, units" },

  // ===== INVENTORY =====
  { code: "inventory.view", module: "INVENTORY", resource: "inventory", action: "view", description: "View inventory" },
  { code: "inventory.receive", module: "INVENTORY", resource: "inventory", action: "receive", description: "Receive goods" },
  { code: "inventory.adjust", module: "INVENTORY", resource: "inventory", action: "adjust", description: "Adjust stock" },
  { code: "inventory.count", module: "INVENTORY", resource: "inventory", action: "count", description: "Perform stock counts" },
  { code: "inventory.transfer", module: "INVENTORY", resource: "inventory", action: "transfer", description: "Transfer stock between branches" },
  { code: "inventory.view_cost", module: "INVENTORY", resource: "inventory", action: "view_cost", description: "View inventory valuation" },

  // ===== PROCUREMENT =====
  { code: "purchase.view", module: "PROCUREMENT", resource: "purchase", action: "view", description: "View purchase documents" },
  { code: "purchase.create", module: "PROCUREMENT", resource: "purchase", action: "create", description: "Create purchase orders" },
  { code: "purchase.edit", module: "PROCUREMENT", resource: "purchase", action: "edit", description: "Edit purchase orders" },
  { code: "purchase.approve", module: "PROCUREMENT", resource: "purchase", action: "approve", description: "Approve purchase orders" },
  { code: "purchase.post", module: "PROCUREMENT", resource: "purchase", action: "post", description: "Post purchase receipts/invoices" },
  { code: "purchase.cancel", module: "PROCUREMENT", resource: "purchase", action: "cancel", description: "Cancel purchase orders" },
  { code: "supplier.view", module: "SUPPLIERS", resource: "supplier", action: "view", description: "View suppliers" },
  { code: "supplier.create", module: "SUPPLIERS", resource: "supplier", action: "create", description: "Create suppliers" },
  { code: "supplier.edit", module: "SUPPLIERS", resource: "supplier", action: "edit", description: "Edit suppliers" },
  { code: "supplier.import", module: "SUPPLIERS", resource: "supplier", action: "import", description: "Import suppliers" },

  // ===== SALES / CUSTOMERS / POS =====
  { code: "sale.view", module: "SALES", resource: "sale", action: "view", description: "View sales transactions" },
  { code: "sale.view_all", module: "SALES", resource: "sale", action: "view_all", description: "View all sales (all cashiers)" },
  { code: "sale.create", module: "SALES", resource: "sale", action: "create", description: "Create sales" },
  { code: "sale.void", module: "SALES", resource: "sale", action: "void", description: "Void sales" },
  { code: "sale.cancel", module: "SALES", resource: "sale", action: "cancel", description: "Cancel sales" },
  { code: "sale.discount", module: "SALES", resource: "sale", action: "discount", description: "Apply discounts" },
  { code: "sale.discount_approve", module: "SALES", resource: "sale", action: "discount_approve", description: "Approve discounts" },
  { code: "sale.credit", module: "SALES", resource: "sale", action: "credit", description: "Authorize credit sales" },
  { code: "sale.refund", module: "SALES", resource: "sale", action: "refund", description: "Process refunds/returns" },
  { code: "sale.price_override", module: "SALES", resource: "sale", action: "price_override", description: "Override sale prices" },
  { code: "customer.view", module: "CUSTOMERS", resource: "customer", action: "view", description: "View customers" },
  { code: "customer.create", module: "CUSTOMERS", resource: "customer", action: "create", description: "Create customers" },
  { code: "customer.edit", module: "CUSTOMERS", resource: "customer", action: "edit", description: "Edit customers" },
  { code: "customer.credit_limit", module: "CUSTOMERS", resource: "customer", action: "credit_limit", description: "Set customer credit limits" },
  { code: "pos.view", module: "POS", resource: "pos", action: "view", description: "View POS terminal" },
  { code: "pos.operate", module: "POS", resource: "pos", action: "operate", description: "Operate POS" },
  { code: "pos.shift_open", module: "POS", resource: "pos", action: "shift_open", description: "Open/close shifts" },
  { code: "pos.cash_manage", module: "POS", resource: "pos", action: "cash_manage", description: "Cash drops and cash-up" },
  { code: "pos.variance_approve", module: "POS", resource: "pos", action: "variance_approve", description: "Approve cash variances" },
  { code: "pos.held", module: "POS", resource: "pos", action: "held", description: "Manage held/suspended sales" },

  // ===== TRANSFERS =====
  { code: "transfer.view", module: "TRANSFERS", resource: "transfer", action: "view", description: "View transfers" },
  { code: "transfer.create", module: "TRANSFERS", resource: "transfer", action: "create", description: "Create transfer requests" },
  { code: "transfer.approve", module: "TRANSFERS", resource: "transfer", action: "approve", description: "Approve transfers" },
  { code: "transfer.dispatch", module: "TRANSFERS", resource: "transfer", action: "dispatch", description: "Dispatch transfers" },
  { code: "transfer.receive", module: "TRANSFERS", resource: "transfer", action: "receive", description: "Receive transfers" },
  { code: "transfer.cancel", module: "TRANSFERS", resource: "transfer", action: "cancel", description: "Cancel transfers" },

  // ===== ACCOUNTING =====
  { code: "accounting.view", module: "ACCOUNTING", resource: "accounting", action: "view", description: "View accounting data" },
  { code: "accounting.post", module: "ACCOUNTING", resource: "accounting", action: "post", description: "Post journal entries" },
  { code: "accounting.reverse", module: "ACCOUNTING", resource: "accounting", action: "reverse", description: "Reverse postings" },
  { code: "accounting.journal_create", module: "ACCOUNTING", resource: "accounting", action: "journal_create", description: "Create manual journal entries" },
  { code: "account.inventory", module: "ACCOUNTING", resource: "account", action: "inventory", description: "Manage chart of accounts" },
  { code: "bank.view", module: "BANKING", resource: "bank", action: "view", description: "View bank accounts" },
  { code: "bank.edit", module: "BANKING", resource: "bank", action: "edit", description: "Manage bank accounts" },
  { code: "bank.reconcile", module: "BANKING", resource: "bank", action: "reconcile", description: "Reconcile bank accounts" },
  { code: "expense.view", module: "EXPENSES", resource: "expense", action: "view", description: "View expenses" },
  { code: "expense.create", module: "EXPENSES", resource: "expense", action: "create", description: "Create expenses" },
  { code: "expense.approve", module: "EXPENSES", resource: "expense", action: "approve", description: "Approve expenses" },
  { code: "report.view", module: "REPORTS", resource: "report", action: "view", description: "View reports" },
  { code: "report.export", module: "REPORTS", resource: "report", action: "export", description: "Export reports" },
  { code: "report.financial", module: "REPORTS", resource: "report", action: "financial", description: "View financial reports (P&L, Balance Sheet, TB)" },

  // ===== HR / PAYROLL =====
  { code: "employee.view", module: "HR", resource: "employee", action: "view", description: "View employees" },
  { code: "employee.create", module: "HR", resource: "employee", action: "create", description: "Create employees" },
  { code: "employee.edit", module: "HR", resource: "employee", action: "edit", description: "Edit employees" },
  { code: "employee.import", module: "HR", resource: "employee", action: "import", description: "Import employees" },
  { code: "hr.view_salaries", module: "HR", resource: "hr", action: "view_salaries", description: "View salary data" },
  { code: "leave.view", module: "HR", resource: "leave", action: "view", description: "View leave" },
  { code: "leave.approve", module: "HR", resource: "leave", action: "approve", description: "Approve leave" },
  { code: "payroll.view", module: "PAYROLL", resource: "payroll", action: "view", description: "View payroll" },
  { code: "payroll.run", module: "PAYROLL", resource: "payroll", action: "run", description: "Run payroll" },
  { code: "payroll.approve", module: "PAYROLL", resource: "payroll", action: "approve", description: "Approve payroll" },
  { code: "payroll.post", module: "PAYROLL", resource: "payroll", action: "post", description: "Post payroll journals" },

  // ===== ASSETS =====
  { code: "asset.view", module: "ASSETS", resource: "asset", action: "view", description: "View fixed assets" },
  { code: "asset.create", module: "ASSETS", resource: "asset", action: "create", description: "Create assets" },
  { code: "asset.edit", module: "ASSETS", resource: "asset", action: "edit", description: "Edit assets" },
  { code: "asset.depreciate", module: "ASSETS", resource: "asset", action: "depreciate", description: "Run depreciation" },
  { code: "asset.dispose", module: "ASSETS", resource: "asset", action: "dispose", description: "Dispose assets" },

  // ===== TAX =====
  { code: "tax.view", module: "TAX", resource: "tax", action: "view", description: "View tax configuration" },
  { code: "tax.edit", module: "TAX", resource: "tax", action: "edit", description: "Configure tax rates" },

  // ===== SETTINGS / SYSTEM =====
  { code: "setting.view", module: "SETTINGS", resource: "setting", action: "view", description: "View system settings" },
  { code: "setting.edit", module: "SETTINGS", resource: "setting", action: "edit", description: "Edit system settings" },
  { code: "audit.view", module: "AUDIT", resource: "audit", action: "view", description: "View audit logs" },
  { code: "approval.view", module: "APPROVALS", resource: "approval", action: "view", description: "View approval requests" },
  { code: "approval.manage", module: "APPROVALS", resource: "approval", action: "manage", description: "Approve/reject requests" },
  { code: "system.manage", module: "SYSTEM", resource: "system", action: "manage", description: "Full system administration" },
];

export const PERMISSION_CODES = PERMISSIONS.map((p) => p.code);

// Default roles with their permission codes
export interface DefaultRoleDef {
  name: string;
  description: string;
  isSystem: boolean;
  isDefault: boolean;
  permissions: string[];
}

const ALL_PERMISSIONS = PERMISSION_CODES;

export const DEFAULT_ROLES: DefaultRoleDef[] = [
  {
    name: "HQ Super Administrator",
    description: "Unrestricted access across all branches and modules",
    isSystem: true,
    isDefault: false,
    permissions: [...ALL_PERMISSIONS],
  },
  {
    name: "HQ Administrator",
    description: "Full administration for HQ configuration and all branches",
    isSystem: true,
    isDefault: false,
    permissions: [...ALL_PERMISSIONS],
  },
  {
    name: "Branch Manager",
    description: "Manages all operations within their assigned branch",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "branch.view",
      "warehouse.view",
      "location.view",
      "department.view",
      "costcentre.view",
      "user.view",
      "product.view",
      "product.create",
      "product.edit",
      "product.price_change",
      "product.view_cost",
      "category.view",
      "inventory.view",
      "inventory.receive",
      "inventory.adjust",
      "inventory.count",
      "inventory.transfer",
      "inventory.view_cost",
      "purchase.view",
      "purchase.create",
      "purchase.edit",
      "purchase.approve",
      "purchase.post",
      "supplier.view",
      "supplier.create",
      "supplier.edit",
      "sale.view",
      "sale.view_all",
      "sale.create",
      "sale.void",
      "sale.cancel",
      "sale.discount",
      "sale.discount_approve",
      "sale.credit",
      "sale.refund",
      "sale.price_override",
      "customer.view",
      "customer.create",
      "customer.edit",
      "customer.credit_limit",
      "pos.view",
      "pos.shift_open",
      "pos.cash_manage",
      "pos.variance_approve",
      "transfer.view",
      "transfer.create",
      "transfer.approve",
      "transfer.dispatch",
      "transfer.receive",
      "accounting.view",
      "bank.view",
      "expense.view",
      "expense.create",
      "expense.approve",
      "report.view",
      "report.export",
      "report.financial",
      "employee.view",
      "leave.view",
      "leave.approve",
      "approval.view",
      "approval.manage",
    ],
  },
  {
    name: "Finance Manager",
    description: "Manages accounting, banking, expenses and financial reporting",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "branch.view",
      "user.view",
      "product.view",
      "product.view_cost",
      "inventory.view",
      "sale.view",
      "sale.view_all",
      "purchase.view",
      "supplier.view",
      "customer.view",
      "accounting.view",
      "accounting.post",
      "accounting.reverse",
      "accounting.journal_create",
      "account.inventory",
      "bank.view",
      "bank.edit",
      "bank.reconcile",
      "expense.view",
      "expense.create",
      "expense.approve",
      "report.view",
      "report.export",
      "report.financial",
      "tax.view",
      "payroll.view",
      "payroll.approve",
      "payroll.post",
      "asset.view",
      "asset.depreciate",
      "setting.view",
      "audit.view",
      "approval.view",
      "approval.manage",
      "sale.discount_approve",
      "sale.credit",
    ],
  },
  {
    name: "Accountant",
    description: "Records transactions, reconciles and produces reports",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "product.view",
      "product.view_cost",
      "inventory.view",
      "sale.view",
      "sale.view_all",
      "purchase.view",
      "supplier.view",
      "customer.view",
      "accounting.view",
      "accounting.post",
      "accounting.journal_create",
      "account.inventory",
      "bank.view",
      "bank.reconcile",
      "expense.view",
      "expense.create",
      "report.view",
      "report.export",
      "report.financial",
      "tax.view",
      "approval.view",
    ],
  },
  {
    name: "Procurement Manager",
    description: "Full procure-to-pay oversight",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "product.view",
      "product.view_cost",
      "inventory.view",
      "inventory.receive",
      "purchase.view",
      "purchase.create",
      "purchase.edit",
      "purchase.approve",
      "purchase.post",
      "purchase.cancel",
      "supplier.view",
      "supplier.create",
      "supplier.edit",
      "report.view",
      "report.export",
      "expense.view",
      "expense.create",
      "approval.view",
      "approval.manage",
    ],
  },
  {
    name: "Procurement Officer",
    description: "Creates purchase documents",
    isSystem: true,
    isDefault: false,
    permissions: [
      "product.view",
      "inventory.view",
      "purchase.view",
      "purchase.create",
      "purchase.edit",
      "supplier.view",
      "supplier.create",
      "report.view",
    ],
  },
  {
    name: "Inventory Manager",
    description: "Manages inventory, counts and transfers",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "product.view",
      "product.create",
      "product.edit",
      "product.view_cost",
      "inventory.view",
      "inventory.receive",
      "inventory.adjust",
      "inventory.count",
      "inventory.transfer",
      "inventory.view_cost",
      "transfer.view",
      "transfer.create",
      "transfer.receive",
      "transfer.cancel",
      "report.view",
      "report.export",
    ],
  },
  {
    name: "Warehouse Manager",
    description: "Manages warehouse operations",
    isSystem: true,
    isDefault: false,
    permissions: [
      "product.view",
      "inventory.view",
      "inventory.receive",
      "inventory.count",
      "transfer.view",
      "transfer.receive",
      "location.view",
      "warehouse.view",
      "report.view",
    ],
  },
  {
    name: "Sales Manager",
    description: "Manages sales team and sales performance",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "product.view",
      "product.view_cost",
      "sale.view",
      "sale.view_all",
      "sale.create",
      "sale.void",
      "sale.discount",
      "sale.discount_approve",
      "sale.credit",
      "sale.refund",
      "sale.price_override",
      "customer.view",
      "customer.create",
      "customer.edit",
      "customer.credit_limit",
      "pos.view",
      "pos.cash_manage",
      "pos.variance_approve",
      "report.view",
      "report.export",
    ],
  },
  {
    name: "Cashier",
    description: "Operates POS and handles cash",
    isSystem: true,
    isDefault: false,
    permissions: [
      "pos.view",
      "pos.operate",
      "pos.shift_open",
      "pos.cash_manage",
      "pos.held",
      "sale.create",
      "sale.view",
      "customer.view",
      "product.view",
      "customer.create",
      "inventory.view",
    ],
  },
  {
    name: "POS Operator",
    description: "Operates the POS terminal",
    isSystem: true,
    isDefault: false,
    permissions: [
      "pos.view",
      "pos.operate",
      "pos.held",
      "sale.create",
      "sale.view",
      "product.view",
      "customer.view",
      "inventory.view",
    ],
  },
  {
    name: "HR Manager",
    description: "Full HR and payroll management",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "employee.view",
      "employee.create",
      "employee.edit",
      "employee.import",
      "hr.view_salaries",
      "leave.view",
      "leave.approve",
      "payroll.view",
      "payroll.run",
      "payroll.approve",
      "payroll.post",
      "report.view",
      "report.export",
      "approval.view",
      "approval.manage",
    ],
  },
  {
    name: "HR Officer",
    description: "HR administration",
    isSystem: true,
    isDefault: false,
    permissions: [
      "employee.view",
      "employee.create",
      "employee.edit",
      "leave.view",
      "leave.approve",
      "report.view",
    ],
  },
  {
    name: "Auditor",
    description: "Read-only financial and operational audit access",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "branch.view",
      "user.view",
      "product.view",
      "product.view_cost",
      "inventory.view",
      "inventory.view_cost",
      "purchase.view",
      "supplier.view",
      "sale.view",
      "sale.view_all",
      "customer.view",
      "transfer.view",
      "accounting.view",
      "bank.view",
      "expense.view",
      "report.view",
      "report.export",
      "report.financial",
      "employee.view",
      "payroll.view",
      "asset.view",
      "audit.view",
      "tax.view",
    ],
  },
  {
    name: "Read Only",
    description: "View-only access to operational data",
    isSystem: true,
    isDefault: false,
    permissions: [
      "dashboard.view",
      "branch.view",
      "product.view",
      "inventory.view",
      "purchase.view",
      "supplier.view",
      "sale.view",
      "customer.view",
      "transfer.view",
      "report.view",
      "employee.view",
    ],
  },
];